server:
  port: ${ORDERS_APP_SERVER_PORT:8081}

spring:
  datasource:
    initialization-mode: always
    data: classpath:data.sql
    url: jdbc:sqlserver://localhost:1443
    username: sa
    password: docker_Password123

client-service:
  host: ${CLIENT_SERVICE_HOST:http://localhost:8080}
