server:
  port: 8081

spring:
  datasource:
    initialization-mode: always
    data: classpath:data.sql
    url: jdbc:postgresql://localhost:5442/clients_db
    username: docker_user
    password: docker_pass